font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        13.0
modify_font cell_height 105%

cursor                  #d698e6
cursor_text_color       #2c1c2e
cursor_shape            beam
cursor_beam_thickness   1.8
cursor_blink_interval   0.6
cursor_stop_blinking_after 10.0

scrollback_lines 10000
scrollback_pager_history_size 0

mouse_hide_wait 2.0
url_style       curly
url_color       #95a9f5
open_url_with   default
copy_on_select  no

repaint_delay   8
input_delay     2
sync_to_monitor yes

enable_audio_bell no
visual_bell_duration 0.0

remember_window_size    yes
window_padding_width    12 14
placement_strategy      center
hide_window_decorations no
confirm_os_window_close 0

tab_bar_edge             bottom
tab_bar_style            powerline
tab_powerline_style      slanted
tab_title_template       " {index}: {title} "
active_tab_foreground    #2c1c2e
active_tab_background    #d698e6
active_tab_font_style    bold
inactive_tab_foreground  #a167a5
inactive_tab_background  #231625
inactive_tab_font_style  normal
tab_bar_background       #1c121e

background              #2c1c2e
foreground              #fde8ff
selection_background    #4f3252
selection_foreground    #fde8ff

color0  #1c121e
color8  #633f66

color1  #f38fad
color9  #f38fad

color2  #ace6b4
color10 #ace6b4

color3  #f9dca1
color11 #f9dca1

color4  #95a9f5
color12 #95a9f5

color5  #d698e6
color13 #ebaaee

color6  #a2e6d6
color14 #98def0

color7  #fde8ff
color15 #f8e0f9

background_opacity      0.92

detect_urls yes

map ctrl+tab            next_tab
map ctrl+shift+tab      previous_tab
map ctrl+shift+f5       load_config_file
