###############
### IMPORTS ###
###############

source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/variables.conf
source = $HOME/.config/hypr/autostart.conf
source = $HOME/.config/hypr/theme.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/keybinds.conf
source = $HOME/.config/hypr/windows.conf


