###################
### KEYBINDINGS ###
###################

$mod = SUPER

bind = $mod, Return, exec, $terminal
bind = ALT, F4, killactive,
bind = $mod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mod, E, exec, $files
bind = $mod, G, togglefloating,
bind = $mod, R, exec, $menu drun
bind = $mod SHIFT, R, exec, $menu run
bind = $mod, F, fullscreen
bind = $mod, V, exec, copyq toggle
bind = $mod SHIFT, B, exec, pkill waybar || waybar
bind = $mod, L, exec, hyprlock
bind = $mod, P, exec, ~/.config/waybar/scripts/powermenu.sh
bind = $mod, slash, exec, python3 ~/.config/rofi/keybinds.py

bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

bind = $mod, Tab, workspace, r+1
bind = $mod SHIFT, Tab, workspace, r-1

bind = $mod SHIFT, S, exec, hyprshot -m region -o ~/Pictures/Screenshots/Screenshot-$(date +%s).png
bind = $mod CTRL, S, exec, hyprshot -m window -o ~/Pictures/Screenshots/Screenshot-$(date +%s).png
bind = , Print, exec, hyprshot -m output -o ~/Pictures/Screenshots/Screenshot-$(date +%s).png

binde = ,XF86AudioRaiseVolume, exec, ~/.config/hypr/scripts/osd.sh vup
binde = ,XF86AudioLowerVolume, exec, ~/.config/hypr/scripts/osd.sh vdown
bind = ,XF86AudioMute, exec, ~/.config/hypr/scripts/osd.sh mute
bind = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
binde = ,XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/osd.sh bup
binde = ,XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/osd.sh bdown

binde = $mod CTRL, right, resizeactive, 30 0
binde = $mod CTRL, left, resizeactive, -30 0
binde = $mod CTRL, up, resizeactive, 0 -30
binde = $mod CTRL, down, resizeactive, 0 30

bindm = $mod, mouse:272, movewindow
bindm = $mod SHIFT, mouse:272, resizewindow
bindl=, switch:on:Lid Switch, exec, systemctl suspend

bind = $mod, W, togglegroup
bind = $mod, bracketright, changegroupactive, f
bind = $mod, bracketleft, changegroupactive, b


