#####################
### LOOK AND FEEL ###
#####################

general {
	gaps_in = 6
	gaps_out = 12
	border_size = 2

	col.active_border = rgb(4f3252)
	col.inactive_border = rgba(4f3252aa)

	resize_on_border = true
	allow_tearing = false
	layout = dwindle
}

group {
	col.border_active = rgb(d698e6)
	col.border_inactive = rgb(4f3252)

	groupbar {
		font_family = JetBrains Mono Nerd Font
		font_size = 10
		col.active = rgb(4f3252)
		col.inactive = rgb(2c1c2e)
		text_color = rgb(fde8ff)
		rounding = 6
		height = 20
		gaps_in = 4
		gaps_out = 4
	}
}

decoration {
	rounding = 12
	rounding_power = 2

	active_opacity = 1.0
	inactive_opacity = 0.94
	fullscreen_opacity = 1.0

	shadow {
		enabled = true
		range = 16
		render_power = 3
		color = rgba(1c121ecc)
		offset = 0 4
		scale = 1.0
	}

	blur {
		enabled = true
		size = 6
		passes = 3
		new_optimizations = true
		xray = false
		noise = 0.02
		contrast = 0.9
		brightness = 0.85
		vibrancy = 0.2
		vibrancy_darkness = 0.0
		special = false
		popups = true
	}
}

animations {
	enabled = true

	bezier = easeOut,		0.16, 1,	0.3,  1
	bezier = easeInOut,		0.87, 0,	0.13, 1
	bezier = spring,	  	0.22, 0.61, 0.36, 1
	bezier = linear,	  	0,	0,	1,	1

	animation = windows,			1, 5,  spring,	popin 70%
	animation = windowsOut,			1, 4,  easeOut,   popin 80%
	animation = windowsMove,		1, 4,  easeInOut
	animation = border,				1, 8,  linear
	animation = borderangle,		1, 80, linear,	loop
	animation = fade,				1, 4,  easeOut
	animation = fadeOut,			1, 4,  easeOut
	animation = workspaces,			1, 5,  easeInOut, fade
	animation = specialWorkspace,	1, 5,  easeInOut, fade
}

dwindle {
	pseudotile = true
	preserve_split = true
	smart_split = false
	smart_resizing = true
}

master {
	new_status = slave
	new_on_top = false
	mfact = 0.55
}

misc {
	disable_hyprland_logo = true
	disable_splash_rendering = true
	force_default_wallpaper = -1
	mouse_move_enables_dpms = true
	key_press_enables_dpms = true
	animate_manual_resizes = true
	animate_mouse_windowdragging = true
	enable_swallow = true
	swallow_regex = ^(kitty)$
	focus_on_activate = true
}

xwayland {
	force_zero_scaling = true
}

windowrule = float on,		  	match:class ^(pavucontrol)$
windowrule = float on,		  	match:class ^(nm-connection-editor)$
windowrule = float on,		  	match:class ^(org.gnome.Calculator)$
windowrule = float on, pin on,  match:title ^(Picture-in-Picture)$
windowrule = size 80% 80%,	  	match:class ^(nemo)$, float on
windowrule = center on,		 	match:class ^(nemo)$,float on
windowrule = opacity 0.92 0.85,	match:class ^(kitty)$
windowrule = opacity 0.95 0.90,	match:class ^(nemo)$
windowrule = opacity 1.0  1.0, 	match:class ^(firefox)$
windowrule = opacity 1.0  1.0, 	match:class ^(code-oss)$
windowrule = opacity 1.0  1.0, 	match:class ^(mpv)$
windowrule = no_blur on,		match:class ^(firefox)$
windowrule = no_blur on,		match:class ^(code-oss)$
